---
- name: checkout Carbon
  git:
    repo: "{{ GRAPHITE_CARBON_GIT_URL }}"
    dest: "{{ graphite_root }}/src/carbon"
    version: "{{ GRAPHITE_CARBON_VERSION }}"

- name: install Carbon dependencies
  pip:
    virtualenv: "{{ graphite_root }}"
    requirements: "{{ graphite_root }}/src/carbon/requirements.txt"

- name: install Carbon
  command: "{{ graphite_root }}/bin/python setup.py install"
  args:
    chdir: "{{ graphite_root }}/src/carbon"
    creates: "{{ graphite_root }}/bin/carbon-cache.py"

- name: configure Carbon and storage
  template:
    src: "carbon/conf/{{ item }}.conf.j2"
    dest: "{{ graphite_root }}/conf/{{ item }}.conf"
  with_items:
    - carbon
    - storage-schemas
    - storage-aggregation
  notify:
    - Restart Carbon

- name: configure Carbon service definition
  template:
    src: carbon/systemd/carbon-cache.service.j2
    dest: /etc/systemd/system/carbon-cache.service
  notify:
    - Restart Carbon

- name: reload systemd unit configuration
  command: systemctl daemon-reload

- name: enable/start the Carbon service
  service:
    name: carbon-cache
    enabled: yes
    state: started
