---
- name: checkout Graphite API
  git:
    repo: "{{ GRAPHITE_API_GIT_URL }}"
    dest: "{{ graphite_root }}/src/api"
    version: "{{ GRAPHITE_API_VERSION }}"

- name: install Graphite API dependencies
  pip:
    virtualenv: "{{ graphite_root }}"
    requirements: "{{ graphite_root }}/src/api/requirements.txt"

- name: install Graphite API
  command: "{{ graphite_root }}/bin/python setup.py install"
  args:
    chdir: "{{ graphite_root }}/src/api"

- name: install Gunicorn
  pip:
    virtualenv: "{{ graphite_root }}"
    name: gunicorn

- name: configure Graphite API
  template:
    src: graphite-api/conf/graphite-api.yml.j2
    dest: "{{ graphite_root }}/conf/graphite-api.yml"
    owner: "{{ graphite_user }}"
    group: "{{ graphite_group }}"
  notify:
    - Restart Graphite

- name: configure systemd unit files for Graphite API
  template:
    src: "graphite-api/systemd/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - graphite-api.socket
    - graphite-api.service
  notify:
    - Restart Graphite

- name: reload systemd unit configuration
  command: systemctl daemon-reload

- name: enable/start Graphite API services
  service:
    name: graphite-api
    enabled: yes
    state: started
