---
GRAPHITE_CARBON_VERSION: "0.9.15"
GRAPHITE_WHISPER_VERSION: "0.9.15"
GRAPHITE_API_VERSION: "1.1.3"

GRAPHITE_ROOT: "/opt/graphite"
GRAPHITE_API_WSGI_PORT: 6000

CARBON_STORAGE_SCHEMAS:
  - name: "carbon"
    description: "Catches all of Carbon's internal metrics"
    pattern: "carbon.*"
    retentions: "10s:1y"
  - name: "default"
    pattern: ".*"
    retentions: "60s:1y"
