---
GRAPHITE_CARBON_VERSION: "0.9.15"
GRAPHITE_WHISPER_VERSION: "0.9.15"
GRAPHITE_API_VERSION: "1.1.3"

graphite_root: "/opt/graphite"
GRAPHITE_NGINX_PORT: 6000

CARBON_STORAGE_SCHEMAS:
  - name: "carbon"
    description: "Catches all of Carbon's internal metrics"
    pattern: "carbon.*"
    retentions: "10s:1y"
  - name: "default"
    pattern: ".*"
    retentions: "60s:1y"

CARBON_STORAGE_AGGREGATIONS:
  - name: "min"
    pattern: "\\.min$"
    xFilesFactor: "0.1"
    aggregationMethod: "min"
  - name: "max"
    pattern: "\\.max$"
    xFilesFactor: "0.1"
    aggregationMethod: "max"
  - name: "sum"
    pattern: "\\.count$"
    xFilesFactor: "0"
    aggregationMethod: "sum"
  - name: "default_average"
    pattern: ".*"
    xFilesFactor: "0.5"
    aggregationMethod: "average"
